# This is like my 3rd re-write of this shit because I'm dumb and keep losing the files, so it's gonna go on github too
# I guess so I don't lose it again Note this is just a fun project for fun. I only am making this because I thought
# it'd be cool to be able to make a message encoder for a number station project I can't imagine how it could be,
# nor if it SHOULD be considering I'm terrible at this, but PLEASE do not use this for anything other than sending
# cryptic and dumb messages between friends I don't take any responsibility if it somehow gets you in trouble

import random
import ConvertToMIDI

encodedMessage = ""
decryptionKey = ""
sMsg = []
sKey = []


def MainNoDrag():
    print(
        "Hello and welcome to Adumbguy's Number Station Generator/Encoder!\n\nTo get started, would you like to pull "
        "a message from a file or enter it manually?")
    print("Enter F or M: ")
    r1 = input()
    if r1.casefold() == "m":
        preCodedMsg = GetManualInput()
    elif r1.casefold() == "f":
        preCodedMsg = GetFileMsg()
    else:
        print("That does not seem to be a valid answer, and I haven't done error handling yet!")

    results = EncodeMessage(ConvertMsgToBin(preCodedMsg))

    print("Would you like to make a midi file of the message? \n")
    r2 = input("(Y/N) : ")

    if r2.casefold() == "y":
        numOfSpaces = 0
        for n in sMsg:
            if n == " ":
                numOfSpaces = numOfSpaces + 1
        print("\nPlease enter a name for the file: ")
        fileName = input()
        ConvertToMIDI.ConvertNumbersToMIDI(results[0], 0, fileName)
        ConvertToMIDI.GeneratePreamble(0, fileName, str(numOfSpaces + 1), results[2])
    
    print("Would you like to write the message and pad to a file? \n")
    r3 = input("(Y/N) : ")
    
    if r3.casefold() == "y":
        WriteTextToFile(results, fileName)
        

def EncodeMessage(cMsg):
    msgNum = ""
    keyNum = ""
    encoded = False
    numTrys = 0
    failed = False
    x = 0
    for n in cMsg:
        if not failed:
            encoded = False
            if n == " ":
                sMsg.append(" ")
                sKey.append(" ")
            else:
                numTrys = 0
                while not encoded:
                    if numTrys <= 99:
                        msgNum = random.randrange(1, 9)
                        keyNum = random.randrange(1, 9)
                        if (msgNum % keyNum) > 0 and n == "1":
                            sMsg.append(str(msgNum))
                            sKey.append(str(keyNum))
                            encoded = True
                        elif (msgNum % keyNum) <= 0 and n == "0":
                            sMsg.append(str(msgNum))
                            sKey.append(str(keyNum))
                            encoded = True
                        else:
                            encoded = False
                            numTrys = numTrys + 1
                    elif numTrys > 99:
                        failed = True
                        break
        elif failed:
            print("It took too many tried to encode the message, try again or tell the dev he sucks")
            break
    jsMsg = ''.join(sMsg)
    jsKey = ''.join(sKey)

    first3Digits = "".join(str(jsKey[0]) + str(jsKey[1]) + str(jsKey[2]))
    
    print("Encoded Message: ", jsMsg)
    print("Decryption Key: ", jsKey)
    return jsMsg, jsKey, first3Digits


def GetManualInput():
    print("\n\nEnter your message here >> ")
    msg = input()
    return msg


def GetFilePath():
    print(
        "Please enter the FULL path to the file you wish to encode\n")
    msgPath = input("PLEASE USE THE FULL PATH: ")
    return msgPath


def GetFileMsg():
    path = GetFilePath()
    msg = ParseFile(path)
    return msg


def ParseFile(path):
    f = open(path, "rt")
    msg = f.read()
    return msg


def ConvertMsgToBin(msg):
    cMsg = ' '.join(format(ord(x), 'b') for x in msg)
    print("Message in Binary: ", cMsg)
    return cMsg


def WriteTextToFile(text, fileName):
    textToWrite = ("This test generated by Adumbguy's Number Station Generator!\n"
                   "Let me know if I royally screwed something up\n"
                   "\n\n\n", text)
    
    with open((fileName + ".txt"), 'w') as f:
        f.write(str(textToWrite))


MainNoDrag()
